add fuzzing engine option

diff --git a/schedule b/schedule
--- a/schedule
+++ b/schedule
@@ -19,6 +19,8 @@ get_cpu_siblings() {
 }
 
 perform_task() {
+    fuzzing_engine=$1
+    shift
     fuzzer=$1
     shift
     fuzzer_dir=$1
@@ -34,6 +36,11 @@ perform_task() {
     min_start=$1
     shift
     
+    if [[ "$fuzzing_engine" != "afl" || "$fuzzing_engine" != "libafl" ]]; then
+        echo "Error: The variable must be either 'afl' or 'libafl', not $fuzzing_engine."
+        exit 1
+    fi
+
     ls $fuzzer_dir > /dev/null
     if [[ ! $? -eq 0 ]]; then
 	echo "ERROR $fuzzer_dir do not exist"
@@ -46,14 +53,14 @@ perform_task() {
     fi
     # Loop from core_start to core_end
     for counter in $(seq 1 ${runs}); do
-        minutes=$(($counter+$min_start-1))
+        minutes=$min_start
         core_id=$(($counter+$cor_start-1))
         if [ $DUMMY == 1 ] ; then
             #dummy
-            echo "docker run --cpuset-cpus="$(get_cpu_siblings $core_id)" --memory="$RAMMAX" --detach --rm -v ${output_dir}-${counter}:/fuzz_out -v ${fuzzer_dir}:/out -e FUZZING_ENGINE=libafl -e TIMEOUT=$timeout -e OUTUID=$(id -u) -e OUTGID=$(id -g) -e CPU_ID_BIND=0 -t osvaldo/oss-base-runner run_fuzzer $fuzzer $*"
+            echo "docker run --cpuset-cpus="$(get_cpu_siblings $core_id)" --memory="$RAMMAX" --detach --rm -v ${output_dir}-${counter}:/fuzz_out -v ${fuzzer_dir}:/out -e FUZZING_ENGINE=$fuzzing_engine -e TIMEOUT=$timeout -e OUTUID=$(id -u) -e OUTGID=$(id -g) -e CPU_ID_BIND=0 -t osvaldo/oss-base-runner run_fuzzer $fuzzer $*"
         else
             #real
-            echo "docker run --cpuset-cpus="$(get_cpu_siblings $core_id)" --memory="$RAMMAX" --detach --rm -v ${output_dir}-${counter}:/fuzz_out -v ${fuzzer_dir}:/out -e FUZZING_ENGINE=libafl -e TIMEOUT=$timeout -e OUTUID=$(id -u) -e OUTGID=$(id -g) -e CPU_ID_BIND=0 -t osvaldo/oss-base-runner run_fuzzer $fuzzer $*"   | at now + $minutes min
+            echo "docker run --cpuset-cpus="$(get_cpu_siblings $core_id)" --memory="$RAMMAX" --detach --rm -v ${output_dir}-${counter}:/fuzz_out -v ${fuzzer_dir}:/out -e FUZZING_ENGINE=$fuzzing_engine -e TIMEOUT=$timeout -e OUTUID=$(id -u) -e OUTGID=$(id -g) -e CPU_ID_BIND=0 -t osvaldo/oss-base-runner run_fuzzer $fuzzer $*"   | at now + $minutes min
         fi
     done
 }
@@ -87,40 +94,20 @@ RUN="3"
 TIME_UNIT=$(convert_to_minutes $TIMEOUT)
 TIME_UNIT=$(($TIME_UNIT+$DELTA))
 
-# #             fuzzer       fuzz_dir                          out_dir_prefx                                run timeout  min_start additional_options
-# #perform_task fuzz_pdfload ~/sut-docker/xpdf-v4.00/baseline/ ~/outputs/pdfload-xpdf-v4.00_baseline-cmplog 5   5m       1         -c
+# #             fuzzing-engine   fuzzer       fuzz_dir                          out_dir_prefx                                run core_start timeout  min_start additional_options
+# #perform_task afl|libafl       fuzz_pdfload ~/sut-docker/xpdf-v4.00/baseline/ ~/outputs/pdfload-xpdf-v4.00_baseline-cmplog 5   0          5m       1         -c
 
-ROUND_TIME=$((TIME_UNIT * 0))
-perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/baseline/ ~/outputs/mbedtls-e483a7_baseline_cmplog $RUN 0 $TIMEOUT $ROUND_TIME -c
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/baseline/ ~/outputs/mbedtls-e483a7_baseline $RUN 3 $TIMEOUT $ROUND_TIME 
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric/ ~/outputs/mbedtls-e483a7_enumetric_cmplog $RUN 6 $TIMEOUT $ROUND_TIME -c
+# ROUND_TIME=$((TIME_UNIT * 0))
+# perform_task afl fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/baseline/ ~/outputs/mbedtls-e483a7_baseline_cmplog $RUN 0 $TIMEOUT $ROUND_TIME -c
+# perform_task afl fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/baseline/ ~/outputs/mbedtls-e483a7_baseline $RUN 3 $TIMEOUT $ROUND_TIME 
+# perform_task afl fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric/ ~/outputs/mbedtls-e483a7_enumetric_cmplog $RUN 6 $TIMEOUT $ROUND_TIME -c
 
 
 # ROUND_TIME=$((TIME_UNIT * 1))
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric/ ~/outputs/mbedtls-e483a7_enumetric $RUN 0 $TIMEOUT $ROUND_TIME 
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric++/ ~/outputs/mbedtls-e483a7_enumetric++_cmplog $RUN 3 $TIMEOUT $ROUND_TIME -c
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric++/ ~/outputs/mbedtls-e483a7_enumetric++ $RUN 6 $TIMEOUT $ROUND_TIME 
+# perform_task libafl fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric/ ~/outputs/mbedtls-e483a7_enumetric $RUN 0 $TIMEOUT $ROUND_TIME 
+# perform_task libafl fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric++/ ~/outputs/mbedtls-e483a7_enumetric++_cmplog $RUN 3 $TIMEOUT $ROUND_TIME -c
+# perform_task libafl fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetric++/ ~/outputs/mbedtls-e483a7_enumetric++ $RUN 6 $TIMEOUT $ROUND_TIME 
 
 
-# ROUND_TIME=$((TIME_UNIT * 2))
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetricbb++/ ~/outputs/mbedtls-e483a7_enumetricbb++_cmplog $RUN 0 $TIMEOUT $ROUND_TIME -c
-# perform_task fuzz_dtlsserver ~/sut-docker/v0.2.6tmp0/mbedtls-e483a7/enumetricbb++/ ~/outputs/mbedtls-e483a7_enumetricbb++ $RUN 3 $TIMEOUT $ROUND_TIME 
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/baseline/ ~/outputs/pcapplusplus-a817631_baseline_cmplog $RUN 6 $TIMEOUT $ROUND_TIME -c
-
-
-# ROUND_TIME=$((TIME_UNIT * 3))
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/baseline/ ~/outputs/pcapplusplus-a817631_baseline $RUN 0 $TIMEOUT $ROUND_TIME 
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/enumetric/ ~/outputs/pcapplusplus-a817631_enumetric_cmplog $RUN 3 $TIMEOUT $ROUND_TIME -c
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/enumetric/ ~/outputs/pcapplusplus-a817631_enumetric $RUN 6 $TIMEOUT $ROUND_TIME 
-
-
-# ROUND_TIME=$((TIME_UNIT * 4))
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/enumetric++/ ~/outputs/pcapplusplus-a817631_enumetric++_cmplog $RUN 0 $TIMEOUT $ROUND_TIME -c
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/enumetric++/ ~/outputs/pcapplusplus-a817631_enumetric++ $RUN 3 $TIMEOUT $ROUND_TIME 
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/enumetricbb++/ ~/outputs/pcapplusplus-a817631_enumetricbb++_cmplog $RUN 6 $TIMEOUT $ROUND_TIME -c
-
-
-# ROUND_TIME=$((TIME_UNIT * 5))
-# perform_task FuzzTarget ~/sut-docker/v0.2.6tmp0/pcapplusplus-a817631/enumetricbb++/ ~/outputs/pcapplusplus-a817631_enumetricbb++ $RUN 0 $TIMEOUT $ROUND_TIME 
 
 get_cpu_siblings 1
